---
- name: restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: restart php-fpm
  service:
    name: "php{{ passbolt_php_default_version_debian }}-fpm"
    state: restarted
    enabled: yes
