---
- name: converge

  hosts: all

  become: true

  roles:

    - wpnops.passbolt

  pre_tasks:

    - name: update apt cache.
      apt:
        update_cache: yes
      when: (ansible_os_family | lower) == 'debian'
      changed_when: False
