---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2004}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: converge.yml
    verify: verify.yml
    side_effect: side_effect.yml
  inventory:
    group_vars:
      all:
        passbolt_bin_path: '/var/www/passbolt/bin'
        passbolt_user: 'www-data'
        passbolt_db_name: passbolt
        passbolt_db_user: passbolt
        passbolt_db_pass: ChangeMe.01!
scenario:
  name: default
verifier:
  name: ansible
scenario:
  converge_sequence:
    - converge
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - side_effect
    - verify
    - destroy
